# collections:
#   authors:
#     output: true

environment: production

# permalink: //:year/:title:output_ext

permalink: /:year/:title:output_ext



plugins:
  - jekyll-seo-tag

name: Jason Crabtree's Blog
title: Jason Crabtree's Blog
description: A personal blog about design, technology, people & society. Customer Operations Operator, Hobbyist Designer, Coffee drinker & overthinker.
author:
  twitter: jasontcrabtree

twitter:
  username: jasontcrabtree
  card: summary

# logo: https://blog.jasontcrabtree.com/assets/favicon.png
# favicon: https://blog.jasontcrabtree.com/assets/favicon.png

image:
  path: https://blog.jasontcrabtree.com/assets/JC-Blog-Image.png
  height: 100
  width: 100

avatar: https://avatars3.githubusercontent.com/u/26457118?s=460&v=4

social:
  name: Jason Crabtree
  links:
    - https://jasontcrabtree.com
    - https://twitter.com/jasontcrabtree.com
    - https://dribbble.com/jasontcrabtree
    - https://www.linkedin.com/in/jasontcrabtree/
    - https://github.com/jasontcrabtree

exclude: [archive]
include: [_redirects]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
