# collections:
#   authors:
#     output: true

environment: production

permalink: //:short_month/:year/:title:output_ext

plugins:
  - jekyll-seo-tag

name: Jason Crabtree's Blog
content: Welcome to the blogzone

meta: Jason Crabtree's Blog
content: A personal blog covering my thoughts on design, technology, people and society.

title: Jason Crabtree's Blog
description: A personal blog where I share my thoughts on design, technology, people and society. Customer Operations Operator, Hobbyist Designer, Coffee drinker and overthinker.
author:
  twitter: jasontcrabtree

twitter:
  username: jasontcrabtree
  card: summary

logo: /assets/favicon.png

social:
  name: Jason Crabtree
  links:
    - https://jasontcrabtree.com
    - https://twitter.com/jasontcrabtree.com
    - https://dribbble.com/jasontcrabtree
    - https://www.linkedin.com/in/jasontcrabtree/
    - https://github.com/jasontcrabtree
    - https://www.linkedin.com

exclude: [archive]
include: [_redirects]

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
