# collections:
#   authors:
#     output: true

environment: production

permalink: //:short_month/:year/:title:output_ext

plugins:
  - jekyll-seo-tag

name: Jason Crabtree's Blog
meta: Jason Crabtree's Blog
content: A personal blog about design, technology, people, society and whatever other stuff I'm thinking about.

title: Jason Crabtree's Blog
description: A personal blog with my thoughts on design, technology, people & society. Customer Operations Operator, Hobbyist Designer, Coffee drinker & overthinker.
author:
  twitter: jasontcrabtree

twitter:
  username: jasontcrabtree
  card: summary

logo: /assets/favicon.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/JC-Blog-Image.png
      author: jasontcrabtree

social:
  name: Jason Crabtree
  links:
    - https://jasontcrabtree.com
    - https://twitter.com/jasontcrabtree.com
    - https://dribbble.com/jasontcrabtree
    - https://www.linkedin.com/in/jasontcrabtree/
    - https://github.com/jasontcrabtree

exclude: [archive]
include: [_redirects]

defaults:
  # - scope:
  #     path: ""
  #     type: "authors"
  #   values:
  #     layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
